HACKATHON/hackathon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('medignore/', include('medignore.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HACKATHON/medignore/urls.py
from django.urls import path
from . import views

app_name = 'medignore'

urlpatterns = [
    # path('service/', views.service, name="service"),
    #path('temp/', views.temp, name="temp"),
    # path('url/<medicine>/', views.url_parse, name="url_parse"),
    path('result/', views.result, name="result"),
    # path('result/', views.result, name="result"),
    # path('search/', views.search, name="search"),
    path('', views.search, name="search"),
    path('clear/',views.clear_database, name='clear_database'),
]

HACKATHON/medignore/models.py
from __future__ import unicode_literals

from django.db import models


class Photo(models.Model):
    title = models.CharField(max_length=255, blank=True)
    photo_file = models.FileField(upload_to='medignore/')

HACKATHON/medignore/forms.py
from django import forms

from .models import Photo


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ('photo_file', )

HACKATHON/medignore/views.py
from django.shortcuts import render
from decouple import config
from urllib.request import Request, urlopen
from urllib.parse import urlencode, quote_plus, unquote
from xml.etree import ElementTree

from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.views import View

from .forms import PhotoForm
from .models import Photo
from .jsonParser import durProhibit, getDurItems

import time
import cv2
import json
import requests
import sys
import re


LIMIT_PX = 1024
LIMIT_BYTE = 1024*1024  # 1MB
LIMIT_BOX = 100


def result(request):
    for photo in Photo.objects.all():
        photo.photo_file.delete()
        photo.delete()
    
    param = request.GET.get('durItems')
    print('dddddd')
    print(param)
    medicine_list = param.split(',')
    prohibit_list1 = durProhibit(medicine_list, '1')
    prohibit_list2 = durProhibit(medicine_list, '2')
    prohibit_list3 = durProhibit(medicine_list, '3')

    medicine_Info1 = zip(medicine_list,prohibit_list1)
    medicine_Info_Result1 = dict(medicine_Info1)

    medicine_Info2 = zip(medicine_list,prohibit_list2)
    medicine_Info_Result2 = dict(medicine_Info2)

    medicine_Info3 = zip(medicine_list,prohibit_list3)
    medicine_Info_Result3 = dict(medicine_Info3)
    
    print(medicine_Info_Result1)
    print(medicine_Info_Result2)
    print(medicine_Info_Result3)
    return render(request,'medignore/result.html',{'medicine_Info_Result1':medicine_Info_Result1,'medicine_Info_Result2':medicine_Info_Result2,'medicine_Info_Result3':medicine_Info_Result3,})
    

def main(request):
    return render(request, 'medignore/main.html')



def search(request):
    kakao_key = config('KAKAO_KEY')
    if request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES)
        if form.is_valid():
            photo = form.save()
            data = {'is_valid': True, 'name': photo.photo_file.name, 'url': photo.photo_file.url}
            image= './'+photo.photo_file.url
            print(f'image url : {image}')
            key = kakao_key
            output = practice(image, key)
            resultOutput =output['result']['recognition_words']
            regex =re.compile('\d{9}')
            medList = list()
            for item in resultOutput:
                mo = regex.search(item)
                if mo != None:
                    medList.append(mo.group())

            data['medList']= medList
            print(f'리스트 출럭{medList}')
            getDurNames=getDurItems(medList)
            data['getDurNames']= getDurNames
            print(getDurNames)
            print(data)
        else:
            data = {'is_valid': False}
        return JsonResponse(data)
    else:  
        photos_list = Photo.objects.all()
        return render(request, 'medignore/search.html', {'photos': photos_list})

def kakao_ocr_resize(image_path: str):
 
    image = cv2.imread(image_path)
    height, width, _ = image.shape

    if LIMIT_PX < height or LIMIT_PX < width:
        ratio = float(LIMIT_PX) / max(height, width)
        image = cv2.resize(image, None, fx=ratio, fy=ratio)
        height, width, _ = height, width, _ = image.shape

        image_path = "{}_resized.jpg".format(image_path)
        cv2.imwrite(image_path, image)

        return image_path
    return None


def kakao_ocr_detect(image_path: str, appkey: str):

    API_URL = 'https://kapi.kakao.com/v1/vision/text/detect'

    headers = {'Authorization': 'KakaoAK {}'.format(appkey)}

    image = cv2.imread(image_path)
    jpeg_image = cv2.imencode(".jpg", image)[1]
    data = jpeg_image.tobytes()

    return requests.post(API_URL, headers=headers, files={"file": data})


def kakao_ocr_recognize(image_path: str, boxes: list, appkey: str):
 
    API_URL = 'https://kapi.kakao.com/v1/vision/text/recognize'

    headers = {'Authorization': 'KakaoAK {}'.format(appkey)}

    image = cv2.imread(image_path)
    jpeg_image = cv2.imencode(".jpg", image)[1]
    data = jpeg_image.tobytes()

    return requests.post(API_URL, headers=headers, files={"file": data}, data={"boxes": json.dumps(boxes)})


def practice(a, b):
    image_path, appkey = a, b
    resize_impath = kakao_ocr_resize(image_path)
    if resize_impath is not None:
        image_path = resize_impath
        print("원본 대신 리사이즈된 이미지를 사용합니다.")

    output = kakao_ocr_detect(image_path, appkey).json()
    print("[detect] output:\n{}\n".format(output))

    boxes = output["result"]["boxes"]
    boxes = boxes[:min(len(boxes), LIMIT_BOX)]
    output = kakao_ocr_recognize(image_path, boxes, appkey).json()
    return output
 

def clear_database(request):
    for photo in Photo.objects.all():
        photo.photo_file.delete()
        photo.delete()
    return redirect(request.POST.get('next'))



# #의약품 낱알식별정보 서비스
# def service(request):
#     #param = request.GET.get('param')
#     serviceKey = config('DATA_API_SERVICEKEY')

#     API_KEY = unquote(serviceKey)
#     url = 'http://apis.data.go.kr/1470000/MdcinGrnIdntfcInfoService/getMdcinGrnIdntfcInfoList'
#     queryParams = '?' + urlencode(
#         {
#             quote_plus('ServiceKey') : API_KEY,
#             quote_plus('item_name'): '디카맥스1000정',
#             #quote_plus('edi_code'): '664600460', 
#         }
#     )

#     request_body = Request(url+queryParams)
#     request_body.get_method = lambda : 'GET'
#     response_body = urlopen(request_body).read().decode('utf-8')

#     print(response_body)

#     return render(request, 'medignore/service.html',{'res':response_body})

HACKATHON/medignore/templates/medignore/_search.html
{% extends 'medignore/base_img.html' %}

{% load static %}

{% block title %}Search{% endblock %}

{% block javascript %}
{# JQUERY FILE UPLOAD SCRIPTS #}
<script src="{% static 'js/jquery-file-upload/vendor/jquery.ui.widget.js' %}"></script>
<script src="{% static 'js/jquery-file-upload/jquery.iframe-transport.js' %}"></script>
<script src="{% static 'js/jquery-file-upload/jquery.fileupload.js' %}"></script>

{# PHOTOS PAGE SCRIPTS #}
<script src="{% static 'medignore/js/drag-and-drop-upload.js' %}"></script>
{% endblock %}


{% block photos_content %}
<form action="/medignore/result/" method="GET">
  검색어 : <input id="searchItems" type="text" name="durItems" style='width :100%'placeholder="약품명을 입력하세요."> <input type="submit" value ="검색">
</form>


<div class="well text-muted text-center" style="padding-top: 4rem; padding-bottom: 4rem;">
  <span class="glyphicon glyphicon-arrow-down" style="font-size: 4rem;"></span>
  <h3>Drop Photos Here to Upload</h3>
</div>



<input id="fileupload" type="file" name="file" multiple style="display: none;" data-url="{% url 'medignore:search' %}"
  data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>

<table id="gallery" class="table table-bordered">
  <thead>
    <tr>
      <th>Photo</th>
    </tr>
  </thead>
  <tbody>
    {% for photo in photos %}
    <tr>
      <td><a href="{{ photo.file.url }}">{{ photo.file.name }}</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<div id="photo">
  {% for photo in photos %}
  <img src="{{ photo.file.url }}">
  {% endfor %}
</div>
{% endblock %}

HACKATHON/medignore/templates/medignore/base_img.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style type="text/css">
      .page-header {
        margin-top: 0;
      }
    </style>
  </head>
  <body>
    <div class="container">
  <form method="post" action="{% url 'medignore:clear_database' %}">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ request.path }}">
    <button type="submit" class="btn btn-danger pull-right">
      <span class="glyphicon glyphicon-trash"></span> 업로드 사진 삭제
    </button>
  </form>
  <h1 class="page-header">
    Medignore
    <small>{% block title %}{% endblock %}</small>
  </h1>
  <div class="row">
    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="list-group">
          <a href="{% url 'medignore:search' %}" class="list-group-item active">
            처방전 이미지를 드로그해서 옮기세요.
          </a>
        </div>
      </div>
    </div>
    <div class="col-md-9">
      {% block photos_content %}
      {% endblock %}
    </div>
  </div>
    </div> 
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block javascript %}
    {% endblock %}
  </body>
</html>

HACKATHON/medignore/templates/medignore/result.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Medignore - 의약품 검색 결과</title>

    <script src="https://kit.fontawesome.com/074b86ccc4.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

    <link rel="stylesheet" href="{% static 'medignore/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'medignore/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'medignore/css/tab.css' %}">
</head>

<body>
    <div id="wrap" class="sub">
        <div id="header">
            <h1 class="logo">
                <a href="/medignore/"><img src="{% static 'medignore/img/logo.png' %}" alt="medignore.io" /></a>
            </h1>
        </div>
        <h2>
            <p><i class="fas fa-search fa-1x"></i> 의약품 검색 결과</p>
        </h2>

        <div class="menu">

            <ul class="menu__tabs">
                <li><a class="active" href="#item-1" class="t1"><span><img src="{% static 'medignore/img/d_icon1.png' %}" alt="임부"></span> 임부</a></li>
                <li><a href="#item-2" class="t2"><span><img src="{% static 'medignore/img/d_icon2.png' %}" alt="노인"></span> 노인</a></li>
                <li><a href="#item-3" class="t3"><span><img src="{% static 'medignore/img/d_icon3.png' %}" alt="유아"></span> 유아</a></li>
            </ul>
            <section class="menu__wrapper">
                <article id="item-1" class="menu__item item-active">
                    <div class="table">
                        <table>
                            <colgroup>
                                <col width="30%">
                                <col width="70%">
                            </colgroup>
                            <thead>
                                <tr>
                                    <th><i class="fas fa-tablets"></i> 약품명</th>
                                    <th><i class="fas fa-caret-down"></i> 부작용</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for key, value in medicine_Info_Result1.items %}
                                <tr>
                                    <td>{{key}}</td>
                                    <td>{{value}}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </article>

                <article id="item-2" class="menu__item">
                    <div class="table old">
                        <table>
                            <colgroup>
                                <col width="30%">
                                <col width="70%">
                            </colgroup>
                            <thead>
                                <tr>
                                    <th><i class="fas fa-tablets"></i> 약품명</th>
                                    <th><i class="fas fa-caret-down"></i> 부작용</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for key, value in medicine_Info_Result2.items %}
                                <tr>
                                    <td>{{key}}</td>
                                    <td>{{value}}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>

                    </div>
                </article>

                <article id="item-3" class="menu__item">
                    <div class="table child">
                        <table>
                            <colgroup>
                                <col width="30%">
                                <col width="70%">
                            </colgroup>
                            <thead>
                                <tr>
                                    <th><i class="fas fa-tablets"></i> 약품명</th>
                                    <th><i class="fas fa-caret-down"></i> 부작용</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for key, value in medicine_Info_Result3.items %}
                                <tr>
                                    <td>{{key}}</td>
                                    <td>{{value}}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </article>

            </section>
        </div>

        <div id="footer">
            <div class="box">
                <div class="icon"><img src="{% static 'medignore/img/copy_img.png' %}" alt="medignore" /></div>
                <p>Copyright ⓒ Medignore. All rights reserved.</p>
            </div>
        </div>

    </div>

    <script>
        $(function() {

            // Menu Tabular
            var $menu_tabs = $('.menu__tabs li a');
            $menu_tabs.on('click', function(e) {
                e.preventDefault();
                $menu_tabs.removeClass('active');
                $(this).addClass('active');

                $('.menu__item').fadeOut(300);
                $(this.hash).delay(300).fadeIn();
            });

            $(".table tr:even").css("background", "#e5e5e5")

        });
    </script>
</body>

</html>

HACKATHON/medignore/templates/medignore/search.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Medignore</title>

    <script src="https://kit.fontawesome.com/074b86ccc4.js" crossorigin="anonymous"></script>

    <!-- <script src="https://unpkg.com/vue/dist/vue.min.js"></script> -->
    <!--<script src="https://cdn.jsdelivr.net/npm/vue@2.5.2/dist/vue.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>-->

    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

    <script src="{% static 'js/jquery-file-upload/vendor/jquery.ui.widget.js' %}"></script>
    <script src="{% static 'js/jquery-file-upload/jquery.iframe-transport.js' %}"></script>
    <script src="{% static 'js/jquery-file-upload/jquery.fileupload.js' %}"></script>
    <script src="{% static 'medignore/js/drag-and-drop-upload.js' %}"></script>

    <link rel="stylesheet" href="{% static 'medignore/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'medignore/css/style.css' %}">
</head>

<body>
    <div id="wrap">
        <div id="header">
            <h1 class="logo">
                <a href="/medignore"><img src="{% static 'medignore/img/logo.png' %}" alt="medignore.io" /></a>
            </h1>
            <p>복용 중인 약에 대한 주의사항을 확인하세요</p>
        </div>
        <div id="content">
            <form action="/medignore/result/" method="GET" id="frm">
                <input type="hidden" id="durItemName" name="durItems" value="">
                <div class="merong">
                    <!--  -->
                    <!--<span v-for="item in list">{% verbatim %}{{ item.name }},{% endverbatim %}</span>-->
                    <span><b></b></span>
                    <!-- 처방전 검색 -->
                    <strong></strong>
                </div>
                <div id="searchForm">
                    <div class="line">
                        <div class="i_box">
                            <div id="inputBox">
                                <input type="text" id="searchText" @input="durItems=$event.target.value" placeholder="약 이름 검색">
                            </div>
                            <div class="btn">
                                <input type="button" value="Search" @click="durSubmit()">
                            </div>
                            <div id="camera"><img src="{% static 'medignore/img/camera.png' %}" alt=""></div>
                        </div>
                        <div id="searchResult" v-if="this.durItems != ''">
                            <ul class="prd_list" v-for="d in filtered">
                                <li v-on:click="addTodo(`${ d.Item }`)">{% verbatim %}{{ d.Item }}{% endverbatim %}</li>
                            </ul>
                        </div>
                    </div>


                </div>
            </form>

            <div class="well text-muted text-center">
                <span class="glyphicon glyphicon-arrow-down" style="font-size: 4rem;"></span>
                <h3><i class="fas fa-file-upload fa-2x"></i>&nbsp;&nbsp;처방전을 드래그앤드롭 해주세요.</h3>
            </div>

            <div class='remove_photo' style="display: none;">
                <form method="post" action="{% url 'medignore:clear_database' %}">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <button type="submit" class="btn btn-danger pull-right">
                      <span class="glyphicon glyphicon-trash"></span> 업로드 사진 삭제
                    </button>
                </form>
            </div>

            <input id="fileupload" type="file" name="photo_file" multiple style="display: none;" data-url="{% url 'medignore:search' %}" data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>

            <table id="gallery" class="table table-bordered" style="display: none;">
                <thead>
                    <tr>
                        <th>Photo</th>
                    </tr>
                </thead>
                <tbody>
                    {% for photo in photos %}
                    <tr>
                        <td><a href="{{ photo.file.url }}">{{ photo.file.name }}</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div id="photo" style="display: none;">
                {% for photo in photos %}
                <img src="{{ photo.file.url }}"> {% endfor %}
            </div>


        </div>

        <script>
            new Vue({
                el: '#content',
                data() {
                    return {
                        durItems: '',
                        data: '',
                    }
                },
                created: function() {
                    axios.get('https://raw.githubusercontent.com/distinctive98/Medignore/dev/HACKATHON/medignore/static/medignore/json/durItems.json')
                        .then(function(response) {
                            // JSON responses are automatically parsed.
                            this.data = response.data['FIELD']
                            console.log(response.data['FIELD'][0]['Item'])

                        }.bind(this)).catch(function(e) {
                            console.error(e)
                        })
                },
                computed: {
                    filtered: function() {
                        var dname = this.durItems.trim();
                        return this.data.filter(function(item, index) {
                            if (item.Item.indexOf(dname) > -1) {
                                return true;
                            }
                        });
                    }
                },
                methods: {
                    addTodo: function(name) {
                        $("#searchText").before("<span class='dur'><span class='close'><i ref='xicon' class='fas fa-times'></i></span><span class='text'>" + name + "</span></span>");
                        $(".merong span").children('b').before('<span>' + name + ',</span>');
                        $("#searchText").val('');

                        return;
                    },

                    durSubmit: function() {
                        var merong = $('.merong').text();
                        //alert(merong)

                        merong = merong.substr(0, merong.length - 2);
                        $('.merong').text(merong);

                        $('#durItemName').attr('value', merong)
                        document.getElementById('frm').submit();
                        return false;


                    },

                }
            })

            $(document).ready(function() {
                $(document).on("click", "span.dur span.close", function(event) {
                    $(this).parent('.dur').remove();

                    //alert(text)
                    var txt = $(this).parent('.dur').children('.text').text()

                    var mr = $('.merong').text()

                    var temp = mr.replace(txt + ',', '');
                    $('.merong').html(temp + '<span><b></b></span>');

                });
            })
        </script>

        <div id="footer">
            <div class="box">
                <div class="icon"><img src="{% static 'medignore/img/copy_img.png' %}" alt="medignore" /></div>
                <p>Copyright ⓒ Medignore. All rights reserved.</p>
            </div>
        </div>
        <a href="https://github.com/distinctive98/Medignore" target="_blank" class="github_corner"><img src="{% static 'medignore/img/icon_github.png' %}" alt="Medignore Github" /></a>
    </div>

</body>

</html>

HACKATHON/medignore/templates/medignore/service.html
{% extends 'medignore/base.html' %}

{% block title %}TEMP{% endblock %}

{% block body %}
<h1 class="text-center">Medignore</h1>
<hr>

<p>{{res.ITEM_NAME}}</p>

{% endblock %}

HACKATHON/medignore/templates/medignore/temp.html
{% block title %}TEMP{% endblock %}

{% block body %}
<h1 class="text-center">Medignore</h1>
<hr>
<div id="app">
    밑에 메세지가 나와야됨
<p>{% verbatim %}{{message}}{% endverbatim %}</p>
</div>
<form action="/medignore/service/">
    <input type="text">
    <button>제출</button>

</form>
<script src="https://cdn.jsdelivr.net/npm/vue@2.5.2/dist/vue.js"></script>


<script>
new Vue({
    el: '#app',
    data: {
        message: '메세지당'
    }
})
</script>
{% endblock %}

HACKATHON/medignore/templates/medignore/test.html
{% extends 'medignore/base.html' %}

{% block title %}TEMP{% endblock %}

{% block body %}
<h1 class="text-center">Medignore</h1>
<hr>
<h3>test</h3>
{% endblock %}